### PR TITLE
A number of fixes discovered during pre-launch testing

### PR DESCRIPTION
**Pull request by hoddr**
Fixes for waitUntilJobCompletes; extend ttl -> update ttl; autoStart bug; waitForCondition refactor

Addresses #11 and #14 in particular.

### CODE REVIEW

**Comment by hoddr** [comment]
Discovered another bug with update ttl function. Working on fix to include in this PR

**Comment by hoddr** [comment]
Bug addressed in commit 5644265

**Review by brimoor — COMMENTED** [review]
LGTM

**Review by brimoor — APPROVED** [review]
LGTM

**Pull request merged**
